# Generated by Django 5.1.15 on 2026-07-04 06:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner", models.CharField(db_index=True, max_length=128)),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="RFC Message-ID header.",
                        max_length=512,
                    ),
                ),
                (
                    "in_reply_to",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                ("references", models.TextField(blank=True, default="")),
                (
                    "thread_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="App-level thread/grouping key.",
                        max_length=512,
                    ),
                ),
                (
                    "delivered_to",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "return_path",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "mailbox",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="eml",
                        help_text="Import source: eml, gmail, imap, ses, sendgrid, etc.",
                        max_length=64,
                    ),
                ),
                ("subject", models.TextField(blank=True, default="")),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "reply_to_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reply_to_email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "date_header",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("to", models.JSONField(blank=True, default=list)),
                ("cc", models.JSONField(blank=True, default=list)),
                ("bcc", models.JSONField(blank=True, default=list)),
                ("text_body", models.TextField(blank=True, default="")),
                ("html_body", models.TextField(blank=True, default="")),
                ("body_preview", models.TextField(blank=True, default="")),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("charset", models.CharField(blank=True, default="", max_length=64)),
                ("is_multipart", models.BooleanField(db_index=True, default=False)),
                (
                    "list_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                ("list_unsubscribe", models.TextField(blank=True, default="")),
                (
                    "precedence",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "feedback_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "notification_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "provider_message_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "spf_result",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "dkim_result",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "dmarc_result",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("authentication_results", models.TextField(blank=True, default="")),
                ("received_spf", models.TextField(blank=True, default="")),
                ("dkim_signature", models.TextField(blank=True, default="")),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("raw_headers", models.TextField(blank=True, default="")),
                (
                    "raw_email",
                    models.BinaryField(
                        blank=True, help_text="Original RFC822 .eml bytes.", null=True
                    ),
                ),
                ("raw_size_bytes", models.PositiveIntegerField(default=0)),
                ("has_attachments", models.BooleanField(db_index=True, default=False)),
                ("attachment_count", models.PositiveIntegerField(default=0)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("is_spam", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("labels", models.JSONField(blank=True, default=list)),
                (
                    "import_batch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        db_index=True,
                        default="parsed",
                        max_length=32,
                    ),
                ),
                ("parse_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ],
            options={
                "db_table": "stored_email",
                "ordering": ["-sent_at", "-received_at"],
                "indexes": [
                    models.Index(fields=["owner", "-sent_at"], name="email_owner_sent"),
                    models.Index(
                        fields=["owner", "is_archived"], name="email_owner_arch"
                    ),
                    models.Index(
                        fields=["from_email", "sent_at"], name="email_from_sent"
                    ),
                    models.Index(fields=["subject"], name="email_subject"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="email_search_gin"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "message_id"), name="uniq_owner_message_id"
                    )
                ],
            },
        ),
    ]
