# Generated by Django 5.1.15 on 2026-07-09 03:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner", models.CharField(db_index=True, max_length=128, unique=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("imap_host", models.CharField(max_length=255)),
                ("imap_port", models.IntegerField(default=993)),
                ("imap_ssl", models.BooleanField(default=True)),
                ("smtp_host", models.CharField(max_length=255)),
                ("smtp_port", models.IntegerField(default=465)),
                (
                    "smtp_security",
                    models.CharField(
                        choices=[
                            ("ssl", "SSL/TLS"),
                            ("starttls", "STARTTLS"),
                            ("none", "None"),
                        ],
                        default="ssl",
                        max_length=16,
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password_enc", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("folders", models.JSONField(blank=True, default=list)),
                ("last_uid", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mail_account",
            },
        ),
    ]
